### ISSUE TITLE
SimpleDigraph doesn't work with `get_edge`

### ISSUE THREAD

**Issue by r-barnes** [scheinerman/SimpleGraphs.jl#6]
`get_edge(G, u, v)` doesn't appear to work on a SimpleDigraph:
```
Closest candidates are:
  get_edge(::SimpleGraph{T}, ::Any, ::Any) where T at /home/rick/.julia/packages/SimpleGraphs/tIcVJ/src/simple_core.jl:197
Stacktrace:
 [1] top-level scope at REPL[88]:1
```

**Comment by scheinerman** [comment]
This isn't a bug or an omission. To test if a graph (simple or directed) has a particular edge, use `has`. 
```julia
julia> G = Cycle(5)
Cycle (n=5, m=5)

julia> has(G,1,2)
true

julia> has(G,2,1)
true

julia> has(G,1,3)
false

julia> H = DirectedCycle(5)
SimpleDigraph{Int64} (n=5, m=5)

julia> has(H,1,2)
true

julia> has(H,2,1)
false
```

The `get_edge` function (which probably is not useful to users and perhaps ought not to be exported) is used to determine how a given edge is stored in the `SimpleGraph`'s data structure. For example:
```julia
julia> get_edge(G,1,2)
(1, 2)

julia> get_edge(G,2,1)
(1, 2)

julia> get_edge(G,1,3)
ERROR: (1,3) is not an edge of this graph
```
In this graph, `G`, there is an edge joining vertices `1` and `2`. The `get_edge` function tells us that in `G`'s edge set, that edge is represented by the tuple `(1,2)`.  For a directed graph, edges `(1,2)` and `(2,1)` are different.
