### ISSUE TITLE
CompatHelper

### ISSUE THREAD

**Issue by willtebbutt** [scheinerman/SimpleGraphs.jl#8]
I notice that this repo doesn't have [CompatHelper](https://github.com/JuliaRegistries/CompatHelper.jl) installed. It's a github action that notifies you whenever one of your dependencies creates a new breaking release. I've personally found it very helpful in keeping my repos up to date, so I thought I would point you towards it in case you've not seen it.

You might also want to look into [TagBot](https://github.com/JuliaRegistries/TagBot) for helping with making releases -- I've certainly found that it makes life easier.

**Comment by scheinerman** [comment]
Thanks for the pointer. I'll need to take a look and see if I can figure out the instructions! All this git and repository stuff is rather a black box for me.

**Comment by willtebbutt** [comment]
Haha I know how you feel. If you would like a reference that you can literally just copy+paste, take a look in the .github/workflows folder [of this repo](https://github.com/JuliaGaussianProcesses/AbstractGPs.jl), specifically the CompatHelper.yml and TagBot.yml files. If you copy+paste them into the same place in this repo, it _should_ just work.
