### ISSUE TITLE
Topological sort

### ISSUE THREAD

**Issue by cscherrer** [scheinerman/SimpleGraphs.jl#9]
@CameronBieganek adapted Graphs.jl to use SimpleGraphs [here](https://discourse.julialang.org/t/lightgraphs-jl-transition/69526/52?u=cscherrer). It would be great for this to be available as part of SimpleGraphs!

cc @jpfairbanks

**Comment by CameronBieganek** [comment]
Actually, that's my own implementation, different from the implementation in Graphs.jl (formerly LightGraphs.jl). Of course, I looked up the algorithm somewhere, possibly Wikipedia. But yes, feel free to use this in SimpleGraphs.jl. :)

**Comment by scheinerman** [comment]
Not sure what's being requested here.

**Comment by jpfairbanks** [comment]
I think @cscherrer would like to add the following code to this package.

```julia
using SimpleGraphs

function topo_sort(g::SimpleDigraph{T}) where {T}
    g = deepcopy(g)
    order = T[]
    s = collect(filter(v -> in_deg(g, v) == 0, vlist(g)))

    while !isempty(s)
        u = pop!(s)
        push!(order, u)

        for v in out_neighbors(g, u)
            delete!(g, u, v)
            if in_deg(g, v) == 0
                push!(s, v)
            end
        end
    end

    if NE(g) > 0
        error("Graph contains cycles.")
    end

    order
end
```

and then export that function from the SimpleGraphs module.

**Comment by cscherrer** [comment]
Thanks @jpfairbanks . It doesn't affect me so much, because I can just use that code locally from Soss. But it could be convenient for other SimpleGraphs users to have this available, and since @CameronBieganek already wrote the code, making it easily available is generally a good thing :)
